Sell_Laptop_Web/Controllers/CpuController.cs
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Sell_Laptop_Web.Controllers
{
    public class CpuController : Controller
    {
        public async Task<IActionResult> Index()
        {

            string apiUrl = "https://localhost:44346/api/Cpu";
            var httpClient = new HttpClient();
            var reponse = await httpClient.GetAsync(apiUrl);
            string apiData = await reponse.Content.ReadAsStringAsync();
            var list = JsonConvert.DeserializeObject<List<Cpu>>(apiData);
            return View(list);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Cpu obj)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44346/api/Cpu");
            var result = client.PostAsJsonAsync<Cpu>(client.BaseAddress, obj).Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, "Thêm thất bại !!!");
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(Cpu x)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44346/api/Cpu");
            var result = client.PutAsJsonAsync(client.BaseAddress, x).Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(string.Empty, "Thêm thất bại !!!");

            return View();
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri($"https://localhost:44346/api/Cpu/id?Id={id}");

                //HTTP DELETE
                var result = client.DeleteAsync(client.BaseAddress).Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            ModelState.AddModelError(string.Empty, "Thất bại !!!");
            return BadRequest();
        }
    }
}

Sell_Laptop_Web/Controllers/HardDriveController.cs
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Sell_Laptop_Web.Controllers
{
    public class HardDriveController : Controller
    {
        public async Task<IActionResult> Index()
        {
            HttpClient client = new HttpClient();
            var reponse = await client.GetAsync("https://localhost:44346/api/HardDrive");
            string apiData = await reponse.Content.ReadAsStringAsync();
            var list = JsonConvert.DeserializeObject<List<HardDrive>>(apiData);
            return View(list);
        }
        public async Task<IActionResult> Create(HardDrive obj)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44346/api/HardDrive");
            var result = client.PostAsJsonAsync(client.BaseAddress, obj).Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {

            return View();
        }
        public async Task<IActionResult> Update(HardDrive obj)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44346/api/HardDrive");
            var result = client.PutAsJsonAsync(client.BaseAddress, obj).Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri($"https://localhost:44346/api/HardDrive/id?Id={id}");
            var result = client.DeleteAsync(client.BaseAddress).Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return BadRequest();
        }
    }
}

Sell_Laptop_Web/Controllers/ImageController.cs
using Data.Models;
using Data.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Sell_Laptop_Web.Controllers
{
    public class ImageController : Controller
    {
        static List<ProductDetailView> listPro;
        public async Task<IActionResult> Index()
        {
            HttpClient client = new HttpClient();
            var reponsePro = await client.GetAsync("https://localhost:44346/api/ProductDetail");
            string apiDataPro = await reponsePro.Content.ReadAsStringAsync();
            listPro = JsonConvert.DeserializeObject<List<ProductDetailView>>(apiDataPro);
            ViewBag.listProductDetail = listPro;
            var reponse = await client.GetAsync("https://localhost:44346/api/Image");
            string apiData = await reponse.Content.ReadAsStringAsync();
            var list = JsonConvert.DeserializeObject<List<Image>>(apiData);
            return View(list);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            HttpClient client = new HttpClient();
            var reponse = await client.GetAsync("https://localhost:44346/api/ProductDetail");
            string apiData = await reponse.Content.ReadAsStringAsync();
            listPro = JsonConvert.DeserializeObject<List<ProductDetailView>>(apiData);
            ViewBag.listProductDetail = listPro;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Image obj, IFormFile imageFile, string maProductDetail)
        {
            HttpClient client = new HttpClient();
            Guid idProductDetail = listPro.FirstOrDefault(x => x.Ma == maProductDetail).Id;
            client.BaseAddress = new Uri("https://localhost:44346/api/Image");
            //  Truyền thêm 1 tham số vào action;
            // Truyền thêm 1 tham số imageFile kiểu IFormFile
            // Bước 1 : Kiểm tra đường dẫn tới ảnh được lấy từ form
            if (imageFile != null && imageFile.Length > 0)// Khác null , khác rỗng
            {
                // Bước 2
                // thực hiện việc trỏ tới mục wwwroot để sau thực viện việc copy
                var path = Path.Combine(Directory.GetCurrentDirectory(),
                    "wwwroot", "UploadImages", imageFile.FileName);
                // Path.Combine : Tổng hợp đường dẫn
                // Kết quả ttt/wwwroot/UploadImages/***.jpg
                var stream = new FileStream(path, FileMode.Create);
                // Thực hiện việc copy => tạo mới => Create
                imageFile.CopyTo(stream);// Coppy ảnh từ form vào thư mục wwwroot/UploadImages
                obj.LinkImage = imageFile.FileName;// Gán giá trị cho thuộc tính LinkImage
                obj.IdProductDetail = idProductDetail;

                var result = client.PostAsJsonAsync(client.BaseAddress, obj).Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(obj);
        }
        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {

            return View();
        }
        public async Task<IActionResult> Update(Image obj, IFormFile imageFile)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44346/api/Image");
            if (imageFile != null && imageFile.Length > 0)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(),
                    "wwwroot", "UploadImages", imageFile.FileName);
                var stream = new FileStream(path, FileMode.Create);
                imageFile.CopyTo(stream);
                obj.LinkImage = imageFile.FileName;


                var result = client.PutAsJsonAsync(client.BaseAddress, obj).Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(obj);
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri($"https://localhost:44346/api/Image/id?Id={id}");
            var result = client.DeleteAsync(client.BaseAddress).Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return BadRequest();
        }
    }
}

Sell_Laptop_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sell_Laptop_Web</title>
@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/Bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sell_Laptop_Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Giới thiệu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Sản phẩm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Khuyến mãi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Đăng nhập</a>
                        </li>

                    </ul>
                    <form class="d-flex" asp-controller="ProductDetail" asp-action="ShowListProduct" role="search" method="get">
                        <input class="form-control me-2" type="search" placeholder="Nhập tên sản phẩm" aria-label="Search" name="nameProduct">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <p></p>
                    <div>
                        <a asp-controller="Cart" asp-action="Index" class="btn btn-outline-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor"
                                 class="bi bi-cart-check" viewBox="0 0 16 16">
                                <path d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z" />
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 
                              2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2
                              0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                            </svg>
                        </a>

                    </div>
                </div>
            </div>

        </nav>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="ProductDetail" asp-action="Index">Chi tiết sản phẩm</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Bill" asp-action="QuanLyBill">Quản lý hóa đơn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Product" asp-action="Index">Sản phẩm</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Producer" asp-action="Index">
                                Nhà sản xuất
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Image" asp-action="Index">Hình ảnh</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Color" asp-action="Index">Màu sắc</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Ram" asp-action="Index">RAM</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Cpu" asp-action="Index">CPU</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="HardDrive" asp-action="Index">HardDrive</a>
                        </li>
                       </div>
                     </div>
                  </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Sell_Laptop_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>